### ISSUE TITLE
test_frag_new is broken

### ISSUE THREAD

**Issue by dbarthel-ol** [openschc/openschc#63]
Trying to run the instructions in https://github.com/openschc/openschc/blob/master/src/README.md, I get the following error message:
$ python3 test_frag_new.py
<<<...>>>
Traceback (most recent call last):
  File "test_frag_new.py", line 131, in <module>
    sim.run()
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/net_sim_core.py", line 337, in run
    self.scheduler.run()
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/net_sim_sched.py", line 40, in run
    callback(*args)
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/net_sim_core.py", line 240, in deliver_packet
    count += self.send_packet_on_link(link, packet)
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/net_sim_core.py", line 307, in send_packet_on_link
    node_to.event_receive(link.from_id, packet)
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/net_sim_core.py", line 96, in event_receive
    self.layer2.event_receive_packet(sender_id, packet)
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/net_sim_layer2.py", line 80, in event_receive_packet
    self.protocol.schc_recv(self.devaddr, packet)
  File "/Users/dominique/Desktop/Hackathon108/openschc/src/protocol.py", line 243, in schc_recv
    dtag_length = frag_rule[T_FRAG][T_FRAG_PROF][T_FRAG_DTAG]
TypeError: 'NoneType' object is not subscriptable

**Comment by tanupoo** [comment]
I don't think test_frag_new.py works with current SCHC layer.  (It was "new" at the one year ago...)
