### ISSUE TITLE
Problem in running  examples/tcp 

### ISSUE THREAD

**Issue by afzal** [openschc/openschc#70]
HI,
I just started to test examples/tcp and i got some errors. Could u please guide me? 

after running  Server on terminal 1 with the command "python3 ClientServerSimul.py --role server --compression false --rule ../configs/rule1.json", I got the following:

socket binded to  127.0.0.1  ip and port  12345
socket is listening
Connexion de 127.0.0.1 34362

then i ran client on another terminal: "python3 ClientServerSimul.py --role client --compression false --rule ../configs/rule1.json --time 20 --payload payload/testfile_small.txt"

Then for both terminal i got the same errors:

--------------------------- Iteration  1  --------------------------
---------- Client: Ip =  127.0.0.1  Port =  34362 ---------------
Traceback (most recent call last):
  File "ClientServerSimul.py", line 100, in <module>
    schcConfig.start()
  File "ClientServerSimul.py", line 70, in start
    self.server.server()
  File "/home/samira/openschc/examples/tcp/ServerConnection.py", line 48, in server
    self.newThread = ClientThread.ClientThread(ipClient, portClient, self.clientSocket, self.configuration)
  File "/home/samira/openschc/examples/tcp/ClientThread.py", line 28, in __init__
    self.client_config()
  File "/home/samira/openschc/examples/tcp/ClientThread.py", line 98, in client_config
    self.clientConfigInServer.configSim()
  File "/home/samira/openschc/examples/tcp/SchcConfig.py", line 68, in configSim
    self.node0 = self.make_node(self.sim, self.rule_manager, self.devaddr)
  File "/home/samira/openschc/examples/tcp/SchcConfig.py", line 85, in make_node
    node = net_sim_core.SimulSCHCNode(sim, extra_config)
  File "../../src/net_sim_core.py", line 89, in __init__
    self.config, self, self.layer2, self.layer3, role, unique_peer)
  File "../../src/protocol.py", line 124, in __init__
    assert role in ["device", "core-server"]
AssertionError

**Comment by tanupoo** [comment]
Hi afzal,  examples/tcp is not probably finished, it's probably in under developing.  You can try udp or gateway instead.
